### ISSUE TITLE
FEATURE - Add parent_id field to stg_jira__field_option

### ISSUE THREAD

**Issue by ltw94** [fivetran/dbt_jira_source#31]
### Is there an existing feature request for this?

- [X] I have searched the existing issues

### Describe the Feature

Hi, if you look at the raw data provided by the Fivetran there is a field called parent_id. Looking at the model stg_jira__field_option, I can see that this is omitted from the final select statement. Could you incldue it please? Thanks!

### Are you interested in contributing this feature?

- [X] Yes.
- [ ] Yes, but I will need assistance and will schedule time during your [office hours](https://calendly.com/fivetran-solutions-team/fivetran-solutions-team-office-hours) for guidance.
- [x] No.

**Comment by fivetran-joemarkiewicz** [comment]
Hi @ltw94 thanks so much for opening this feature request!

This seems like a reasonable addition to the staging model. However, we do not leverage this field internally and I am not entirely sure what the `parent_id` is within the context of the `field_option` table. Would you be able to add some context as to what this field is and how you leverage it?

**Comment by ltw94** [comment]
Hi! Yes this was a request from one of our Analysts who says:

In Jira when defining custom fields you can create parent and child fields (to define main category and sub-categories).  For example, the possible options of the child (i.e Modbus,HTTPS,SFTP…) depend on the selected parent option (i.e Protocols). 
Since the issue_field_history it’s only saved the child option, the parent_id is needed to know which is the parent of the child.

**Comment by fivetran-joemarkiewicz** [comment]
Thanks for the context @ltw94!

That makes sense as to why you would want to bring the `parent_id` into the staging model. I don't see any risk in bringing the field into this staging model. However, at the moment we do not incorporate the `parent_id` in any downstream models within the `dbt_jira` package. Is this something you would expect to see propagated in those downstream models?

If so, then we can open a FR on the dbt_jira repo to investigate possible avenues for including the fields in those. In the meantime, adding the `parent_id` to the staging model would not be too much of a lift. I noticed you marked that you were interested in creating a PR. Is that something you are still interested in pursuing? If so, let me know if I can help you with next steps for opening a PR and contributing to the package 😄

**Comment by ltw94** [comment]
Hi! Apologies for the delayed response. For now our analysis is only of the field_option table and our own downstream models, and haven't considered propagation to downstream models of the dbt-package.

Given that, I would say for the time being it would make most sense to just include the parent_id in the staging_model :) 
For us the main key is speed, so if it's faster that we open the PR ourselves then we can do so (I see this blog post here: https://discourse.getdbt.com/t/contributing-to-an-external-dbt-package/657) which seems relatively straight forward for us to go ahead with.

**Comment by fivetran-joemarkiewicz** [comment]
That makes sense to me and it would be great to have your contribution to the open-source package! 

The link you provided is great to follow for contributing. Once you open the PR I will be sure to expedite the review and work with you to merge the changes into the package for you and other to leverage. 

Let me know if you have any questions when opening the PR!

**Comment by alejobs** [comment]
Hi,

Many thanks for moving forward this issue! I saw that the MR was merged, but you forgot to do the release of the latest version (0.4.2). Can you please do it so that we can leverage the latest change? @fivetran-joemarkiewicz 

Thanks!

**Comment by fivetran-joemarkiewicz** [comment]
@alejobs thanks so much for bumping this! I just cut the release. Thanks again so much for your contribution 😄
