### ISSUE TITLE
SLA metrics missing

### ISSUE THREAD

**Issue by ant0inemtr** [fivetran/dbt_jira_source#4]
Hi!

While playing with the dbt jira models you've released, I came across the fact that `sla` table doesn't seem to be included in source tables (dbt_jira_source). 

As a result, in the dbt__jira repo, jira__issue_enhanced (and maybe jira__user_enhanced) would be even more useful if they could get the sla metrics in their models! 👍  

It'd be a great feature in order to track Support Team performance.
Thanks a lot,
Antoine

**Comment by fivetran-kristin** [comment]
Hi @ant0inemtr!

We currently don't support this, as the sample dataset we used to model this package did not have this information.  We'd be happy to add this to our package if we can somehow get access to data.

If you're interested in sharing your data with us temporarily so we can build this, feel free to book some time with me [here](http://5tran.co/office-hours) and I'll walk you through the process.

Thanks!
Kristin

**Comment by ant0inemtr** [comment]
Hi!

Great, I'll book a slot so that I can share you this in the following weeks, thanks!

**Comment by fivetran-kristin** [comment]
Hey @ant0inemtr - just checking in here, is this still something you're interested in?

**Comment by fivetran-kristin** [comment]
@ant0inemtr I'm assuming this is no longer a priority. If it is, please reopen this issue and we'll reassess.  Thanks!
