### ISSUE TITLE
jira_using_sprints is not referenced in jira_source

### ISSUE THREAD

**Issue by bbirand** [fivetran/dbt_jira_source#5]
Should this line

https://github.com/fivetran/dbt_jira_source/blob/930bf8468a6e91b29e0fe5cea6ff507f6d5a4feb/dbt_project.yml#L23

not be a reference to `sprint: "{{ source('jira', 'jira_using_sprints') }}"` similar to the other lines?

**Comment by fivetran-kristin** [comment]
Hi @bbirand - this `jira_using_sprints` is a variable used to disable any tables related to Sprints.  More information about this is [here](https://github.com/fivetran/dbt_jira_source#disabling-models).
