### ISSUE TITLE
Allow user to disable JIRA source table: component

### ISSUE THREAD

**Issue by curious-bryan** [fivetran/dbt_jira_source#7]
Our org does not use the components feature for JIRA issues.  So Fivetran does not pipe that data in.  It would be nice to have dbt ignore building models related to the JIRA source table _component_ so that an error is not thrown in dbt run when trying to build `stg_jira__component_tmp`.

The docs say that a source JIRA table can be excluded by adding `false` to the corresponding variable name in `dbt_project.yml` file. 

```
vars:
  jira_source:
    component: false
```

However, doing this for component table seems tell dbt to build `stg_jira__component_tmp` from a table in the `DB.schema` named `FALSE`.

```
002003 (42S02): SQL compilation error:
  Object 'DB.SCHEMA.FALSE' does not exist or not authorized.
  compiled SQL at target/run/jira_source/models/tmp/stg_jira__component_tmp.sql
```

**Comment by fivetran-kristin** [comment]
@curious-bryan Thanks for bringing up this issue!  I've just introduced a new variable, `jira_using_components` which allows you to easily disable all component related logic.  More on how to do this is [here](https://github.com/fivetran/dbt_jira_source#disabling-models).

Upgrade to our latest version of the package (jira source v0.1.3 or jira v0.1.5) to make use of this new feature.
