### ISSUE TITLE
add source model for jira.field_option table

### ISSUE THREAD

**Issue by IrinaSel** [fivetran/dbt_jira_source#8]
We are experimenting with jira package models and also have some custom models which are dependent on field_option table from jira schema. We prefer not to mix custom staging table from jira with jira_source package models and would like to have this table in this package as well.

**Comment by fivetran-kristin** [comment]
@IrinaSel thanks for this recommendation! We've just added in a new model, `stg_jira__field_option` which does just this.  

Upgrade to our latest version of the package (jira source v0.1.3 or jira v0.1.5) to make use of this new feature.
